whiteducksoftware/flock

.vscode/settings.json
pyproject.toml
src/flock/__init__.py
src/flock/core/flock.py
src/flock/core/logging/formatters/pprint_formatter.py

fixed otel runtime warnings
fixed default output formatter
added show_cli_banner to hide cute flock cli banner

fixed runtime warnings // fixed default output // add disable cli_banner flag

---

pyproject.toml
src/flock/config.py
src/flock/core/flock.py
src/flock/core/flock_agent.py
src/flock/core/logging/telemetry.py
src/flock/core/mixin/dspy_integration.py
src/flock/core/registry/agent_registry.py

Fix TelemetryId being empty in logging

fix telemetry id

---

README.md

This PR removes the X social media badges and adds BlueSky and LinkedIn badged

docs: replace X social badge with LinkedIn and Bluesky badges

---

pyproject.toml
src/flock/core/flock_agent.py

versioning
use_cache per default true

versioning

---

pyproject.toml
src/flock/modules/output/output_module.py

Add no_output option to OutputModule to suppress output

---

.project/tasks/US007-T006-YAML-Editor-CLI.md
pyproject.toml
src/flock/__init__.py
src/flock/cli/constants.py
src/flock/cli/registry_management.py

registry cli

---

pyproject.toml
src/flock/core/flock.py
tests/core/test_flock_core.py
tests/serialization/test_file_path_serialization.py

fix all existing tests

---

src/flock/core/context/context.py
src/flock/core/execution/temporal_executor.py
src/flock/workflow/agent_execution_activity.py
src/flock/workflow/flock_workflow.py
src/flock/workflow/temporal_setup.py

exectute_single_agent and determine_next_agent activities for temporal process

---

pyproject.toml
src/flock/modules/assertion/assertion_module.py
src/flock/modules/callback/callback_module.py
src/flock/modules/memory/memory_module.py
src/flock/modules/output/output_module.py
src/flock/modules/performance/metrics_module.py
src/flock/modules/zep/zep_module.py

fix parameter order

---

pyproject.toml
src/flock/core/flock_agent.py

fix wait for input

---

pyproject.toml
src/flock/core/mixin/dspy_integration.py
src/flock/core/util/input_resolver.py
src/flock/core/util/spliter.py
uv.lock

remove broken splitters and use new implementation where applicable

---

.gitignore
pyproject.toml
src/flock/core/util/spliter.py

improve signature parser.
added bunch of validation examples

fix signature

---

pyproject.toml
src/flock/cli/manage_agents.py
src/flock/core/api/endpoints.py
src/flock/core/flock_agent.py
src/flock/webapp/templates/partials/_agent_detail_form.html
src/flock/webapp/templates/partials/_agent_list.html

added resolved_description for easier description access

helper "resolved_description"

---

pyproject.toml
src/flock/webapp/app/api/execution.py
src/flock/webapp/app/chat.py
src/flock/webapp/app/config.py
src/flock/webapp/app/main.py
src/flock/webapp/templates/base.html
src/flock/webapp/templates/chat.html
src/flock/webapp/templates/partials/_agent_detail_form.html
src/flock/webapp/templates/partials/_flock_properties_form.html
src/flock/webapp/templates/partials/_results_display.html
src/flock/webapp/templates/partials/_structured_data_view.html
src/flock/webapp/templates/shared_run_page.html
uv.lock

fixes: small formatiing fixes
fixes: small path issues (saving agents and flocks)
fix: better default theme

formatting fixes

---

README.md
pyproject.toml

added high-level changelog to readme
---
no
---
---

added high-level changelog to readme

---

README.md
pyproject.toml

Added MCP info to readme
---
#100 
---
---

Added MCP info to readme

---

.github/workflows/deploy-documentation.yml
.github/workflows/deploy-whiteduck-pypi.yml
docs/getting-started/configuration.md
docs/guides/temporal-configuration.md
src/flock/cli/execute_flock.py

Changed the workflow triggers for build&publish and docs pipeline to main
---

fix: workflows trigger from master to main

---

pyproject.toml

Just for triggering deployment

versioning for triggering workflow

---

pyproject.toml
src/flock/webapp/templates/chat.html
src/flock/webapp/templates/partials/_chat_messages.html
uv.lock

fix: #111 
will now behave correctly
---
#111 
---
---

fix: #111 - chat feedback formular always open in standalone mode

---

.github/workflows/deploy-whiteduck-pypi.yml

sync submodule
feat: [skip publish] will make a pr/merge with no publish and just the build afterwards
---
---

feat: [skip publish] will make a pr/merge with no publish and just the build afterwards / sync submodule

---

pyproject.toml
src/flock/webapp/app/main.py

When serving Flock with flock.serve(chat=True) the standalone chat works but the in-app chat isn't there and the sidebar doesn't display the chat menu items.
This is now fixed
---
#98 
---
---

fix: #98 - Fix/chat in sidebar

---

pyproject.toml
src/flock/webapp/app/main.py
uv.lock

fix: https proxy to route server https to webapp http
---
---

fix: https proxy to route server https to webapp http

---

pyproject.toml
src/flock/webapp/templates/partials/_settings_theme_content.html
src/flock/webapp/templates/partials/_theme_preview.html

fix: theme preview in webapp
Theme preview will now change the whole page again so you can try out a theme before commiting to it
---
---

fix: themes form preview

---

pyproject.toml
src/flock/core/flock_factory.py
src/flock/evaluators/declarative/declarative_evaluator.py

👔 add include_reasoning in declarative evaluator and flock_factory

👔 add include_reasoning in declarative evaluator and flock_factory

---

pyproject.toml
src/flock/webapp/app/api/execution.py
uv.lock

fixed pydantic+json issues. now using FastAPI json encoder
---
---
---

🐛 other json issue fixed

---

pyproject.toml
uv.lock

Fix dependency. neo4j and sentence-transformers to main deps
---
---
---

➕ fix deps

---

pyproject.toml
src/flock/webapp/app/services/sharing_store.py

🐛 fix a crash when generating sharable links
---
---
---

🐛 fix a crash when generating sharable links

---

pyproject.toml

An additional dependency has been introduced in the PR for Issue: #152 
The dependency in question is [`werkzeug`](https://pypi.org/project/Werkzeug/)

added werkzeug-package as dependency

---

pyproject.toml
src/flock/webapp/app/api/execution.py
src/flock/webapp/app/chat.py
src/flock/webapp/app/services/feedback_file_service.py
src/flock/webapp/app/services/sharing_store.py
src/flock/webapp/templates/partials/_execution_form.html
src/flock/webapp/templates/partials/_registry_viewer_content.html
uv.lock

Patch branch to resolve merge-conflicts

0.5.0b patch 2

---

pyproject.toml
src/flock/core/flock.py
uv.lock

remove llm proxy // update packages

---

pyproject.toml
src/flock/tools/web_tools.py
src/flock/tools/zendesk_tools.py
uv.lock

zendesk add comment

---

.gitignore
pyproject.toml
src/flock/components/evaluation/declarative_evaluation_component.py
src/flock/components/utility/output_utility_component.py
src/flock/core/agent/default_agent.py
src/flock/core/util/cli_helper.py
uv.lock

feat: cli table stream

---

pyproject.toml
requirements.txt

fix: otel deps

---

.github/workflows/deploy-whiteduck-pypi.yml
.github/workflows/quality.yml
pyproject.toml
src/flock/dashboard/service.py
src/flock/engines/dspy_engine.py
src/flock/orchestrator.py
tests/test_dashboard_launcher.py
uv.lock

fix: flock 0.5 quality gates and CI

---

pyproject.toml

chore: versioning

---

pyproject.toml
src/flock/helper/cli_helper.py

fix: frontend build package
